# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MoverConfiguratorMain(object):
    def setupUi(self, MoverConfiguratorMain):
        MoverConfiguratorMain.setObjectName("MoverConfiguratorMain")
        MoverConfiguratorMain.setEnabled(True)
        MoverConfiguratorMain.resize(821, 291)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MoverConfiguratorMain.sizePolicy().hasHeightForWidth())
        MoverConfiguratorMain.setSizePolicy(sizePolicy)
        MoverConfiguratorMain.setMinimumSize(QtCore.QSize(300, 200))
        MoverConfiguratorMain.setMaximumSize(QtCore.QSize(1920, 1080))
        MoverConfiguratorMain.setAutoFillBackground(True)
        MoverConfiguratorMain.setAnimated(True)
        MoverConfiguratorMain.setDocumentMode(False)
        MoverConfiguratorMain.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MoverConfiguratorMain)
        self.centralwidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_3.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_3.setSpacing(4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.findFolderButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.findFolderButton.sizePolicy().hasHeightForWidth())
        self.findFolderButton.setSizePolicy(sizePolicy)
        self.findFolderButton.setMinimumSize(QtCore.QSize(0, 30))
        self.findFolderButton.setMaximumSize(QtCore.QSize(300, 30))
        self.findFolderButton.setObjectName("findFolderButton")
        self.horizontalLayout_3.addWidget(self.findFolderButton, 0, QtCore.Qt.AlignTop)
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setMaximumSize(QtCore.QSize(250, 30))
        self.textEdit.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout_3.addWidget(self.textEdit, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 3, 0, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.gridLayout_2.addLayout(self.formLayout, 4, 0, 1, 1)
        self.verticalScrollBar = QtWidgets.QScrollBar(self.centralwidget)
        self.verticalScrollBar.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.gridLayout_2.addWidget(self.verticalScrollBar, 3, 1, 1, 1)
        MoverConfiguratorMain.setCentralWidget(self.centralwidget)

        self.retranslateUi(MoverConfiguratorMain)
        QtCore.QMetaObject.connectSlotsByName(MoverConfiguratorMain)

    def retranslateUi(self, MoverConfiguratorMain):
        _translate = QtCore.QCoreApplication.translate
        MoverConfiguratorMain.setWindowTitle(_translate("MoverConfiguratorMain", "MoverConfigurator"))
        self.findFolderButton.setText(_translate("MoverConfiguratorMain", "Ricerca cartella"))
        self.textEdit.setDocumentTitle(_translate("MoverConfiguratorMain", "folderName"))
